language: generic
sudo: required
services:
  - docker
    
before_install: 
  - docker build -t rajesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rajesh/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "FirstDocker"
   env: "Docker-env"
   bucket_name: "" # code copied to s3 bucket
   bucket_path: "docker"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
