language: generic
sudo: required
services:
  - docker
    
before_install: 
  - docker build -t rajesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rajesh/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: 'us-east-2'
   app: 'firstdocker'
   env: 'docker-env'
   bucket_name: 'Firstdocker-env.eba-zenpzqqe.us-east-2.elasticbeanstalk.com'
   bucket_path: 'docker'
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
